### ISSUE TITLE
js files not loading

### ISSUE THREAD

**Issue by OkuraSt** [mtbvang/sails-generate-reactjs-gulp#1]
Hi
Im very interested in building sails applications with react, and Im trying to get this generator working
Ive followed sails-generate-new-gulp instructions, with the .sailsrc file Ive created my sails aplication for gulp, after that I modify the .sailsrc created for my sails application to match the sails-generate-reactjs-gulp generator.

First problem I encountered was:
![image](https://cloud.githubusercontent.com/assets/9710146/8581454/77926940-2586-11e5-8dd5-f0d20d61fd2e.png)
Ive tried running these commands as administrator, but no luck, I've deleted all folders created by the first generator (assets, config, tasks, etc) and then the react generator seemed to work, but after I npm installed everything and lift the app, something appears to be missing:
![image](https://cloud.githubusercontent.com/assets/9710146/8581553/24af468e-2587-11e5-9783-ebf92741b0e4.png)

Im new with these technologies so I appreciate the help.

**Comment by mtbvang** [comment]
@OkuraSt Try adding --force to the end of the command and let me know if that fixes it.

**Comment by mtbvang** [comment]
@OkuraSt you also need to do a 'sails generate bower' as well to install the bower dependencies. I'll update the docs. Hope that gets it going.

**Comment by OkuraSt** [comment]
Thank you for the quick response, 
I started the process again with the new directions, it seems different this time but its not working perfectly. After the command "sails generate reactjs" Ive installed the corresponding bower-gulp generator, installed bower dependencies with "bower install", installed npm dependencies with "npm install" and lifted the application.

Now it shows like this:
![image](https://cloud.githubusercontent.com/assets/9710146/8584010/f845da84-2597-11e5-80a9-eae8e35a310b.png)
and the Todo example like this:
![image](https://cloud.githubusercontent.com/assets/9710146/8584022/0ec1aeaa-2598-11e5-90cf-d4ae1cb64fdd.png)

What I see is that, jsx files are being copied but not converted to JS, this is my public js directory:
![image](https://cloud.githubusercontent.com/assets/9710146/8584044/37c776ea-2598-11e5-9ce8-68cbc56e7147.png)

Is something extra I need to do? Again thank you very much.

**Comment by mtbvang** [comment]
@OkuraSt The jsx is converted and copied over using the gulp react:dev task. I haven't added the "gulp-react": "^3.0.1" dependency to the devDependencies section of the package.json file. yet. Try installing that dependency and then your sails lift should transform the jsx and copy them over. You can also run the task directly using 'gulp react:dev'.

**Comment by OkuraSt** [comment]
@mtbvang Thank you man, it works now.
All these diferent technologies, npm, bower, gulp, etc, Im barely grasping it, :(.
I'll try to use this component now:
https://www.npmjs.com/package/material-ui
Ill see if it works.
